#!/usr/bin/env bash

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended
_baz() {
    _init_completion -s || return

    local cur=${COMP_WORDS[COMP_CWORD]}
    local comp_line="${COMP_WORDS[@]:1}"

    case "$comp_line" in
    'install local'*) COMPREPLY=($(compgen -A directory -- "$cur")) ;;
    'install git'*) COMPREPLY=($(compgen -W "git:// https:// git+https:// http:// git+http://" -- "$cur")) ;;
    'info exist'*) COMPREPLY=($(compgen -W "$([ -d "$HOME/.local/share/baz/plugins" ] && find "$HOME/.local/share/baz/plugins" -not -path . -and -not -path "$HOME/.local/share/baz/plugins" -maxdepth 1 -type d)" -- "$cur")) ;;
    'info local'*) COMPREPLY=($(compgen -A directory -- "$cur")) ;;
    'uninstall'*) COMPREPLY=($(compgen -W "$([ -d "$HOME/.local/share/baz/plugins" ] && find "$HOME/.local/share/baz/plugins" -not -path . -and -not -path "$HOME/.local/share/baz/plugins" -maxdepth 1 -type d)" -- "$cur")) ;;
    'info git'*) COMPREPLY=($(compgen -W "git:// https:// git+https:// http:// git+http://" -- "$cur")) ;;
    'install'*) COMPREPLY=($(compgen -W "local git" -- "$cur")) ;;
    'update'*) COMPREPLY=($(compgen -W "$([ -d "$HOME/.local/share/baz/plugins" ] && find "$HOME/.local/share/baz/plugins" -not -path . -and -not -path "$HOME/.local/share/baz/plugins" -maxdepth 1 -type d)" -- "$cur")) ;;
    'info'*) COMPREPLY=($(compgen -W "exist local git" -- "$cur")) ;;
    ''*) COMPREPLY=($(compgen -W "help setup unsetup install uninstall list update info upgrade version" -- "$cur")) ;;
    esac
} && complete -F _baz -o bashdefault -o default baz
